"""
Module 5 Package — Quantum Execution & Backend Integration Layer.

Exposes physicalization contracts, physicalization engine, backend capability models,
native gate translation models, execution contracts, execution engine, verifiers, serializers, and package metadata.
"""

from src.module5.physical_ir import (
    PhysicalQubit,
    QubitMapping,
    DeviceTopology,
    PhysicalGateOperation,
    PhysicalCircuitIR,
    ExecutionProvenance,
    SCHEMA_VERSION,
    PhysicalCircuitValidationResult,
    validate_physical_circuit_ir,
    serialize_physical_circuit_ir,
    deserialize_physical_circuit_ir,
)
from src.module5.backend import (
    BackendType,
    BackendIdentity,
    QubitCapacity,
    BackendTopologyCapability,
    GateCapability,
    GateConstraint,
    MeasurementCapability,
    ExecutionCapability,
    NumericalCapability,
    BackendCapabilityProvenance,
    BackendCapabilityModel,
    BACKEND_CAPABILITY_SCHEMA_VERSION,
    CapabilityValidationResult,
    validate_backend_capabilities,
    BackendCompatibilityResult,
    validate_backend_compatibility,
    serialize_backend_capabilities,
    deserialize_backend_capabilities,
    create_reference_simulator_capabilities,
)
from src.module5.physicalization import (
    InitialMapper,
    ShortestPathRouter,
    RoutingEvent,
    RoutingTrace,
    PhysicalizationVerificationResult,
    SemanticPreservationVerifier,
    PhysicalizationEngine,
)
from src.module5.native import (
    NativeGateDefinition,
    NativeOperation,
    NativeResolutionStatus,
    NativeGateResolutionResult,
    NativeCircuitIR,
    NativeTranslationResult,
    NATIVE_SCHEMA_VERSION,
    NativeGateVocabulary,
    DecompositionEntry,
    GateDecompositionRegistry,
    BackendAdapter,
    ReferenceBackendAdapter,
    NativeCircuitValidationResult,
    validate_native_circuit_ir,
    SemanticVerificationReport,
    NativeCircuitVerifier,
    NativeTranslator,
    serialize_native_circuit_ir,
    deserialize_native_circuit_ir,
)
from src.module5.execution import (
    ExecutionMode,
    ExecutionStatus,
    ExecutionFailureCode,
    MeasurementResult,
    ExecutionRequest,
    ExecutionResult,
    EXECUTION_SCHEMA_VERSION,
    STAGE_5_EPSILON,
    RequestValidationResult,
    ResultValidationResult,
    validate_execution_request,
    validate_execution_result,
    serialize_execution_request,
    deserialize_execution_request,
    serialize_execution_result,
    deserialize_execution_result,
    QuantumState,
    apply_x,
    apply_cnot,
    apply_swap,
    apply_toffoli,
    apply_h,
    apply_z,
    apply_s,
    apply_t,
    apply_cz,
    apply_native_operation,
    ShotSampler,
    ExecutionEngine,
    ExecutionEquivalenceReport,
    ExecutionVerifier,
)

__version__ = "0.5.0-alpha"
__status__ = "STAGE_5_STEP_3_COMPLETE"

__all__ = [
    # Stage 1 Physical IR
    "PhysicalQubit",
    "QubitMapping",
    "DeviceTopology",
    "PhysicalGateOperation",
    "PhysicalCircuitIR",
    "ExecutionProvenance",
    "SCHEMA_VERSION",
    "PhysicalCircuitValidationResult",
    "validate_physical_circuit_ir",
    "serialize_physical_circuit_ir",
    "deserialize_physical_circuit_ir",

    # Stage 2 Backend Capabilities
    "BackendType",
    "BackendIdentity",
    "QubitCapacity",
    "BackendTopologyCapability",
    "GateCapability",
    "GateConstraint",
    "MeasurementCapability",
    "ExecutionCapability",
    "NumericalCapability",
    "BackendCapabilityProvenance",
    "BackendCapabilityModel",
    "BACKEND_CAPABILITY_SCHEMA_VERSION",
    "CapabilityValidationResult",
    "validate_backend_capabilities",
    "BackendCompatibilityResult",
    "validate_backend_compatibility",
    "serialize_backend_capabilities",
    "deserialize_backend_capabilities",
    "create_reference_simulator_capabilities",

    # Stage 3 Physicalization & Routing
    "InitialMapper",
    "ShortestPathRouter",
    "RoutingEvent",
    "RoutingTrace",
    "PhysicalizationVerificationResult",
    "SemanticPreservationVerifier",
    "PhysicalizationEngine",

    # Stage 4 Native Gate Translation
    "NativeGateDefinition",
    "NativeOperation",
    "NativeResolutionStatus",
    "NativeGateResolutionResult",
    "NativeCircuitIR",
    "NativeTranslationResult",
    "NATIVE_SCHEMA_VERSION",
    "NativeGateVocabulary",
    "DecompositionEntry",
    "GateDecompositionRegistry",
    "BackendAdapter",
    "ReferenceBackendAdapter",
    "NativeCircuitValidationResult",
    "validate_native_circuit_ir",
    "SemanticVerificationReport",
    "NativeCircuitVerifier",
    "NativeTranslator",
    "serialize_native_circuit_ir",
    "deserialize_native_circuit_ir",

    # Stage 5 Execution Contracts & Engine
    "ExecutionMode",
    "ExecutionStatus",
    "ExecutionFailureCode",
    "MeasurementResult",
    "ExecutionRequest",
    "ExecutionResult",
    "EXECUTION_SCHEMA_VERSION",
    "STAGE_5_EPSILON",
    "RequestValidationResult",
    "ResultValidationResult",
    "validate_execution_request",
    "validate_execution_result",
    "serialize_execution_request",
    "deserialize_execution_request",
    "serialize_execution_result",
    "deserialize_execution_result",
    "QuantumState",
    "apply_x",
    "apply_cnot",
    "apply_swap",
    "apply_toffoli",
    "apply_h",
    "apply_z",
    "apply_s",
    "apply_t",
    "apply_cz",
    "apply_native_operation",
    "ShotSampler",
    "ExecutionEngine",
    "ExecutionEquivalenceReport",
    "ExecutionVerifier",
]
